enabled: True
python: |
  def for_try_except_break_finally():
    res = []
    for num in [1, 2]:
      try:
        result = num // 0
      except ZeroDivisionError:
        print("Sorry ! You are dividing by zero ")
        break
      else:
        pass
      finally:
        res.append(num)
    
    return res == [1]